//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.21 at 04:27:48 AM WET 
//


package com.lyncode.xliff.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.lyncode.xliff.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.lyncode.xliff.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Xliff.File.Body }
     * 
     */
    public Xliff.File.Body createXliffFileBody() {
        return new Xliff.File.Body();
    }

    /**
     * Create an instance of {@link Xliff }
     * 
     */
    public Xliff createXliff() {
        return new Xliff();
    }

    /**
     * Create an instance of {@link Xliff.File }
     * 
     */
    public Xliff.File createXliffFile() {
        return new Xliff.File();
    }

    /**
     * Create an instance of {@link TransUnit }
     * 
     */
    public TransUnit createTransUnit() {
        return new TransUnit();
    }

}
